{
 "title": "LOGLAS",
 "time": { "from": "2019-04-21T19:52:58.858Z", "to": "2020-04-23T21:52:58.860Z" },
 "panels": [
  {
   "title": "See players into lobby now",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(regtime,$__interval),\n  lobbyId AS \"Lobby Id\",\n  count(playerCount) AS \"Players Now\"\nFROM LOBBY_REGTIME\nGROUP BY  lobbyId"
    }
   ]
  },
  {
   "title": "See Lobby ID & playerLimit",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  createDate AS \"time\",\n  id AS \"Lobby Id\",\n  playerLimit AS \"Player Limit\"\nFROM LOBBY\nWHERE\n  $__timeFilter(createDate)\nORDER BY createDate"
    }
   ]
  },
  {
   "title": "Total Players ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(createDate,$__interval),\n  sum(playerCount) AS \"playerCount\"\nFROM LOBBY\nWHERE\n  $__timeFilter(createDate)\nGROUP BY 1\nORDER BY $__timeGroup(createDate,$__interval)"
    }
   ]
  },
  {
   "title": "Most played games",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(LOBBY.createDate) as time_sec,\n  count(LOBBY.gameId) as \"Quantity\", \n  GAME.title as \"Game\"\nFROM LOBBY join GAME on LOBBY.gameId = GAME.id\n\nWHERE $__timeFilter(LOBBY.createDate)\ngroup by gameId,createDate\nORDER BY LOBBY.createDate ASC\n"
    }
   ]
  }
 ]
}